name: Build and Release wgsetup

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install shiv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create dist directory
      run: mkdir dist

    - name: Build executable with shiv
      run: |
        shiv -c main -o dist/wgsetup \
          --python '/usr/bin/env python3' .

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/wgsetup
        name: Release ${{ github.ref_name }}
        body: |
          Release ${{ github.ref_name }}
          
          ## Usage
          Download the `wgsetup` executable and run it directly:
          ```bash
          chmod +x wgsetup
          sudo ./wgsetup
          ```